import { Product } from './types/Product';

export const sampleProducts: Product[] = [
{   
    _id: '1',
    name: 'Canon EOS 2000D',
    slug: 'canon-eos-2000D',
    category: 'Camera',
    image: '../images/p1.jpg',
    price: 5999,
    countInStock: 10,
    brand: 'Canon',
    rating: 4.5,
    numReviews: 10,
    description: 'high qualiy 24MP',
},
{
    _id: '2',
    name: 'Canon EOS 2000D',
    slug: 'canon-eos-2000D',
    category: 'Camera',
    image: '../images/p1.jpg',
    price: 5999,
    countInStock: 10,
    brand: 'Canon',
    rating: 4.5,
    numReviews: 10,
    description: 'high qualiy 24MP',
},
{
    _id: '3',
    name: 'Canon EOS 2000D',
    slug: 'canon-eos-2000D',
    category: 'Camera',
    image: '../images/p1.jpg',
    price: 5999,
    countInStock: 10,
    brand: 'Canon',
    rating: 4.5,
    numReviews: 10,
    description: 'high qualiy 24MP',
},
{
    _id: '4',
    name: 'Canon EOS 2000D',
    slug: 'canon-eos-2000D',
    category: 'Camera',
    image: '../images/p1.jpg',
    price: 5999,
    countInStock: 10,
    brand: 'Canon',
    rating: 4.5,
    numReviews: 10,
    description: 'high qualiy 24MP',
},
]